### ISSUE TITLE
[SUGGESTION] Kill Timer on Arrows

### ISSUE THREAD

**Issue by Coswics** [edayot/grappling_hook#1]
if an arrow doesnt land after a set amount of time, or goes into unloaded chunks, this can cause extreme rubberbanding when that chunk is loaded/the arrow finally lands, i think there should be a timer (not despawn) that kills the arrow after a set amount of seconds.; and the arrows range in general is kinda insane,  can be used to rubberband up w/extreme momentum 

love the datapack in general though, keep up the great work

https://github.com/user-attachments/assets/52de693e-9d4e-442a-aed6-1f8c4ec1ec28

**Comment by Coswics** [comment]
maybe have the tag to kill the arrows be separate per grappling hook, diff timers for the basic, normal, and advanced hooks

**Comment by Coswics** [comment]
Another thing, you can right click the grappling hooks before the arrow lands (on all hooks, not just the advanced one) to get boosted early

**Comment by Coswics** [comment]
Secondary Suggestion, if it hits an entity, drag that entity towards the one who fired the arrow? (basically running in reverse)

**Comment by edayot** [comment]
I'm hearing these suggestions, I will certainly add more limitations on the velocity you can have depending on the level. Right clicking early is actually coded as a feature but I will certainly restrict it to the advanced one, and the entity suggestion isn't bad at all.

**Comment by Coswics** [comment]
yeah i thought that the right clicking early was a bug on the basic and normal ones, considering it's able to be done on all of them/the advanced elytra was described as "If correctly used, you can fly with it" (and since you can charge one up and right click on another in your inventory to boost early); I appreciate you considering these suggestions as well ^w^

**Comment by Coswics** [comment]
getting the arrows' owner data to kill that arrow specifically might be best, if this is used in a multiplayer environment where multiple can be thrown/shot at once

**Comment by edayot** [comment]
I was always using `execute on origin` to get the player from the arrow, so i don't think there is a problem

**Comment by edayot** [comment]
Thank you, i will close this issue as i finished the work needed.
