### ISSUE TITLE
Buggy Textures

### ISSUE THREAD

**Issue by aWheatField** [edayot/grappling_hook#3]
The textures are bugged on 1.21.3 I'm playing on a Lunar Hosted World.

![image](https://github.com/user-attachments/assets/bffd2328-b735-4191-964a-700bd203c686)

**Comment by edayot** [comment]
Do you have the resource pack enabled ?, if yes can you share your game logs ?

**Comment by Maybes2** [comment]
> Do you have the resource pack enabled ?, if yes can you share your game logs ?

Has this issue been resolved? This had happened when i downloaded it into my world. Is there a resource pack, as you said

**Comment by edayot** [comment]
No, this issue is not resolved, and yes there is a required ressource pack

**Comment by Maybes2** [comment]
> No, this issue is not resolved, and yes there is a required ressource pack

where would this resource pack be? I tried looking for it but I have yet to find it

**Comment by edayot** [comment]
On [github](https://github.com/edayot/grappling_hook/releases/tag/v1.2.1) and [modrinth](https://modrinth.com/datapack/grappling_hook/version/1.2.1) it's `grappling_hook_1.2.1_rp_bundled.zip` the one you are looking for

**Comment by Maybes2** [comment]
> On [github](https://github.com/edayot/grappling_hook/releases/tag/v1.2.1) and [modrinth](https://modrinth.com/datapack/grappling_hook/version/1.2.1) it's `grappling_hook_1.2.1_rp_bundled.zip` the one you are looking for

okay so i just downloaded the rp and the book finally does have the correct textures thanks
